services:
  postgres:
    image: postgres:16
    container_name: qualifyze_pg
    environment:
      POSTGRES_USER: qualifyze
      POSTGRES_PASSWORD: qualifyze
      POSTGRES_DB: qualifyze
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: