-- with exact as (
--     select
--         a.audit_id,
--         a.site_name as audit_site_name,
--         a.site_address as audit_site_address,
--         a.site_city,
--         a.site_country,
--         s.site_id as exact_site_id
--     from staging.stg_audits a
--     left join staging.stg_sitesdb s
--         on lower(a.site_name) = lower(s.site_name)
--        and lower(a.site_address) = lower(s.address)
-- ),

-- fuzzy_candidates as (
--     select
--         e.audit_id,
--         s.site_id as resolved_site_id,
--         similarity(lower(e.audit_site_name), lower(s.site_name)) as name_score,
--         similarity(lower(e.audit_site_address), lower(s.address)) as address_score
--     from exact e
--     join staging.stg_sitesdb s
--         on lower(e.site_city) = lower(s.city)
--        and lower(e.site_country) = lower(s.country)
--     where e.exact_site_id is null
-- ),

-- fuzzy_best as (
--     select *,
--         row_number() over (partition by audit_id order by least(name_score, address_score) desc) as rn
--     from fuzzy_candidates
--     where least(name_score, address_score) >= 0.3
-- )

-- select
--     e.audit_id,
--     e.audit_site_name,
--     e.audit_site_address,
--     s.site_id,
--     s.site_name,
--     s.address as site_address,
--     case
--         when e.exact_site_id is not null then 'exact_name'
--         when fb.resolved_site_id is not null then 'fuzzy_combined'
--         else 'no match found'
--     end as match_method,
--     case when e.exact_site_id is not null then 1.0 else round(fb.name_score::numeric, 2) end as name_score,
--     case when e.exact_site_id is not null then 1.0 else round(fb.address_score::numeric, 2) end as address_score
-- from exact e
-- left join fuzzy_best fb on fb.audit_id = e.audit_id and fb.rn = 1
-- left join staging.stg_sitesdb s on s.site_id = coalesce(e.exact_site_id, fb.resolved_site_id)
-- order by match_method, e.audit_id;

select count(distinct audit_id) from staging.audit_sites_matches